version: '3.5'

services:
    node-bots:
    container_name: node-bots
    image: mazbaz/yticket-bots:master

    environment:
      - API_URL=https://yticket.mazbaz.fr/api
      - TELEGRAM_TOKEN=
      - DISCORD_TOKEN=
      - WS_HOST=node-bots
      - WS_PORT=8080
      - WS_URL=node-bots:8080
    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.node-bots.loadbalancer.server.port=80"
      - "traefik.http.routers.node-bots.service=node-bots"
      - "traefik.http.routers.node-bots.rule=Host(`yticket-wss.mazbaz.fr`)"
      - "traefik.http.routers.node-bots.entrypoints=web"
      